name: WinGo History Logger

on:
  schedule:
    - cron: "*/1 * * * *"   # every minute
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run logger
        run: python logger.py

      - name: Commit log
        run: |
          touch history_log.txt
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add history_log.txt
          git commit -m "log update" || echo "No changes"
          git push
